### ISSUE TITLE
era bine sa schimbi in interfata category in getCategory, cum ai facut cu Name

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs16-code.homeworks#4]
https://github.com/cezarhre/curs16-code.homeworks/blob/0112d091bd240df82df0b3b911d19ef940b678ef/src/main/java/ro/fasttrackit/curs16/homeworks/Fruits.java#L31

**Comment by cezarhre** [comment]
Este schimbata mai sus
